# Generated by Django 5.0.6 on 2024-08-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Images/slide')),
                ('name', models.CharField(max_length=50)),
                ('tilte', models.CharField(max_length=50)),
            ],
        ),
    ]
